using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace ProdApi_2.Migrations
{
    /// <inheritdoc />
    public partial class Initial : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Countries",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "character varying(60)", maxLength: 60, nullable: false),
                    Alpha2 = table.Column<string>(type: "character varying(2)", maxLength: 2, nullable: false),
                    Alpha3 = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                    Region = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Countries", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "Id", "Alpha2", "Alpha3", "Name", "Region" },
                values: new object[,]
                {
                    { 1, "AF", "AFG", "Afghanistan", "Asia" },
                    { 2, "AX", "ALA", "Åland Islands", "Europe" },
                    { 3, "AL", "ALB", "Albania", "Europe" },
                    { 4, "DZ", "DZA", "Algeria", "Africa" },
                    { 5, "AS", "ASM", "American Samoa", "Oceania" },
                    { 6, "AD", "AND", "Andorra", "Europe" },
                    { 7, "AO", "AGO", "Angola", "Africa" },
                    { 8, "AI", "AIA", "Anguilla", "Americas" },
                    { 9, "AQ", "ATA", "Antarctica", "" },
                    { 10, "AG", "ATG", "Antigua and Barbuda", "Americas" },
                    { 11, "AR", "ARG", "Argentina", "Americas" },
                    { 12, "AM", "ARM", "Armenia", "Asia" },
                    { 13, "AW", "ABW", "Aruba", "Americas" },
                    { 14, "AU", "AUS", "Australia", "Oceania" },
                    { 15, "AT", "AUT", "Austria", "Europe" },
                    { 16, "AZ", "AZE", "Azerbaijan", "Asia" },
                    { 17, "BS", "BHS", "Bahamas", "Americas" },
                    { 18, "BH", "BHR", "Bahrain", "Asia" },
                    { 19, "BD", "BGD", "Bangladesh", "Asia" },
                    { 20, "BB", "BRB", "Barbados", "Americas" },
                    { 21, "BY", "BLR", "Belarus", "Europe" },
                    { 22, "BE", "BEL", "Belgium", "Europe" },
                    { 23, "BZ", "BLZ", "Belize", "Americas" },
                    { 24, "BJ", "BEN", "Benin", "Africa" },
                    { 25, "BM", "BMU", "Bermuda", "Americas" },
                    { 26, "BT", "BTN", "Bhutan", "Asia" },
                    { 27, "BO", "BOL", "Bolivia (Plurinational State of)", "Americas" },
                    { 28, "BQ", "BES", "Bonaire, Sint Eustatius and Saba", "Americas" },
                    { 29, "BA", "BIH", "Bosnia and Herzegovina", "Europe" },
                    { 30, "BW", "BWA", "Botswana", "Africa" },
                    { 31, "BV", "BVT", "Bouvet Island", "Americas" },
                    { 32, "BR", "BRA", "Brazil", "Americas" },
                    { 33, "IO", "IOT", "British Indian Ocean Territory", "Africa" },
                    { 34, "BN", "BRN", "Brunei Darussalam", "Asia" },
                    { 35, "BG", "BGR", "Bulgaria", "Europe" },
                    { 36, "BF", "BFA", "Burkina Faso", "Africa" },
                    { 37, "BI", "BDI", "Burundi", "Africa" },
                    { 38, "CV", "CPV", "Cabo Verde", "Africa" },
                    { 39, "KH", "KHM", "Cambodia", "Asia" },
                    { 40, "CM", "CMR", "Cameroon", "Africa" },
                    { 41, "CA", "CAN", "Canada", "Americas" },
                    { 42, "KY", "CYM", "Cayman Islands", "Americas" },
                    { 43, "CF", "CAF", "Central African Republic", "Africa" },
                    { 44, "TD", "TCD", "Chad", "Africa" },
                    { 45, "CL", "CHL", "Chile", "Americas" },
                    { 46, "CN", "CHN", "China", "Asia" },
                    { 47, "CX", "CXR", "Christmas Island", "Oceania" },
                    { 48, "CC", "CCK", "Cocos (Keeling) Islands", "Oceania" },
                    { 49, "CO", "COL", "Colombia", "Americas" },
                    { 50, "KM", "COM", "Comoros", "Africa" },
                    { 51, "CG", "COG", "Congo", "Africa" },
                    { 52, "CD", "COD", "Congo, Democratic Republic of the", "Africa" },
                    { 53, "CK", "COK", "Cook Islands", "Oceania" },
                    { 54, "CR", "CRI", "Costa Rica", "Americas" },
                    { 55, "CI", "CIV", "Côte d'Ivoire", "Africa" },
                    { 56, "HR", "HRV", "Croatia", "Europe" },
                    { 57, "CU", "CUB", "Cuba", "Americas" },
                    { 58, "CW", "CUW", "Curaçao", "Americas" },
                    { 59, "CY", "CYP", "Cyprus", "Asia" },
                    { 60, "CZ", "CZE", "Czechia", "Europe" },
                    { 61, "DK", "DNK", "Denmark", "Europe" },
                    { 62, "DJ", "DJI", "Djibouti", "Africa" },
                    { 63, "DM", "DMA", "Dominica", "Americas" },
                    { 64, "DO", "DOM", "Dominican Republic", "Americas" },
                    { 65, "EC", "ECU", "Ecuador", "Americas" },
                    { 66, "EG", "EGY", "Egypt", "Africa" },
                    { 67, "SV", "SLV", "El Salvador", "Americas" },
                    { 68, "GQ", "GNQ", "Equatorial Guinea", "Africa" },
                    { 69, "ER", "ERI", "Eritrea", "Africa" },
                    { 70, "EE", "EST", "Estonia", "Europe" },
                    { 71, "SZ", "SWZ", "Eswatini", "Africa" },
                    { 72, "ET", "ETH", "Ethiopia", "Africa" },
                    { 73, "FK", "FLK", "Falkland Islands (Malvinas)", "Americas" },
                    { 74, "FO", "FRO", "Faroe Islands", "Europe" },
                    { 75, "FJ", "FJI", "Fiji", "Oceania" },
                    { 76, "FI", "FIN", "Finland", "Europe" },
                    { 77, "FR", "FRA", "France", "Europe" },
                    { 78, "GF", "GUF", "French Guiana", "Americas" },
                    { 79, "PF", "PYF", "French Polynesia", "Oceania" },
                    { 80, "TF", "ATF", "French Southern Territories", "Africa" },
                    { 81, "GA", "GAB", "Gabon", "Africa" },
                    { 82, "GM", "GMB", "Gambia", "Africa" },
                    { 83, "GE", "GEO", "Georgia", "Asia" },
                    { 84, "DE", "DEU", "Germany", "Europe" },
                    { 85, "GH", "GHA", "Ghana", "Africa" },
                    { 86, "GI", "GIB", "Gibraltar", "Europe" },
                    { 87, "GR", "GRC", "Greece", "Europe" },
                    { 88, "GL", "GRL", "Greenland", "Americas" },
                    { 89, "GD", "GRD", "Grenada", "Americas" },
                    { 90, "GP", "GLP", "Guadeloupe", "Americas" },
                    { 91, "GU", "GUM", "Guam", "Oceania" },
                    { 92, "GT", "GTM", "Guatemala", "Americas" },
                    { 93, "GG", "GGY", "Guernsey", "Europe" },
                    { 94, "GN", "GIN", "Guinea", "Africa" },
                    { 95, "GW", "GNB", "Guinea-Bissau", "Africa" },
                    { 96, "GY", "GUY", "Guyana", "Americas" },
                    { 97, "HT", "HTI", "Haiti", "Americas" },
                    { 98, "HM", "HMD", "Heard Island and McDonald Islands", "Oceania" },
                    { 99, "VA", "VAT", "Holy See", "Europe" },
                    { 100, "HN", "HND", "Honduras", "Americas" },
                    { 101, "HK", "HKG", "Hong Kong", "Asia" },
                    { 102, "HU", "HUN", "Hungary", "Europe" },
                    { 103, "IS", "ISL", "Iceland", "Europe" },
                    { 104, "IN", "IND", "India", "Asia" },
                    { 105, "ID", "IDN", "Indonesia", "Asia" },
                    { 106, "IR", "IRN", "Iran (Islamic Republic of)", "Asia" },
                    { 107, "IQ", "IRQ", "Iraq", "Asia" },
                    { 108, "IE", "IRL", "Ireland", "Europe" },
                    { 109, "IM", "IMN", "Isle of Man", "Europe" },
                    { 110, "IL", "ISR", "Israel", "Asia" },
                    { 111, "IT", "ITA", "Italy", "Europe" },
                    { 112, "JM", "JAM", "Jamaica", "Americas" },
                    { 113, "JP", "JPN", "Japan", "Asia" },
                    { 114, "JE", "JEY", "Jersey", "Europe" },
                    { 115, "JO", "JOR", "Jordan", "Asia" },
                    { 116, "KZ", "KAZ", "Kazakhstan", "Asia" },
                    { 117, "KE", "KEN", "Kenya", "Africa" },
                    { 118, "KI", "KIR", "Kiribati", "Oceania" },
                    { 119, "KP", "PRK", "Korea (Democratic People's Republic of)", "Asia" },
                    { 120, "KR", "KOR", "Korea, Republic of", "Asia" },
                    { 121, "KW", "KWT", "Kuwait", "Asia" },
                    { 122, "KG", "KGZ", "Kyrgyzstan", "Asia" },
                    { 123, "LA", "LAO", "Lao People's Democratic Republic", "Asia" },
                    { 124, "LV", "LVA", "Latvia", "Europe" },
                    { 125, "LB", "LBN", "Lebanon", "Asia" },
                    { 126, "LS", "LSO", "Lesotho", "Africa" },
                    { 127, "LR", "LBR", "Liberia", "Africa" },
                    { 128, "LY", "LBY", "Libya", "Africa" },
                    { 129, "LI", "LIE", "Liechtenstein", "Europe" },
                    { 130, "LT", "LTU", "Lithuania", "Europe" },
                    { 131, "LU", "LUX", "Luxembourg", "Europe" },
                    { 132, "MO", "MAC", "Macao", "Asia" },
                    { 133, "MG", "MDG", "Madagascar", "Africa" },
                    { 134, "MW", "MWI", "Malawi", "Africa" },
                    { 135, "MY", "MYS", "Malaysia", "Asia" },
                    { 136, "MV", "MDV", "Maldives", "Asia" },
                    { 137, "ML", "MLI", "Mali", "Africa" },
                    { 138, "MT", "MLT", "Malta", "Europe" },
                    { 139, "MH", "MHL", "Marshall Islands", "Oceania" },
                    { 140, "MQ", "MTQ", "Martinique", "Americas" },
                    { 141, "MR", "MRT", "Mauritania", "Africa" },
                    { 142, "MU", "MUS", "Mauritius", "Africa" },
                    { 143, "YT", "MYT", "Mayotte", "Africa" },
                    { 144, "MX", "MEX", "Mexico", "Americas" },
                    { 145, "FM", "FSM", "Micronesia (Federated States of)", "Oceania" },
                    { 146, "MD", "MDA", "Moldova, Republic of", "Europe" },
                    { 147, "MC", "MCO", "Monaco", "Europe" },
                    { 148, "MN", "MNG", "Mongolia", "Asia" },
                    { 149, "ME", "MNE", "Montenegro", "Europe" },
                    { 150, "MS", "MSR", "Montserrat", "Americas" },
                    { 151, "MA", "MAR", "Morocco", "Africa" },
                    { 152, "MZ", "MOZ", "Mozambique", "Africa" },
                    { 153, "MM", "MMR", "Myanmar", "Asia" },
                    { 154, "NA", "NAM", "Namibia", "Africa" },
                    { 155, "NR", "NRU", "Nauru", "Oceania" },
                    { 156, "NP", "NPL", "Nepal", "Asia" },
                    { 157, "NL", "NLD", "Netherlands", "Europe" },
                    { 158, "NC", "NCL", "New Caledonia", "Oceania" },
                    { 159, "NZ", "NZL", "New Zealand", "Oceania" },
                    { 160, "NI", "NIC", "Nicaragua", "Americas" },
                    { 161, "NE", "NER", "Niger", "Africa" },
                    { 162, "NG", "NGA", "Nigeria", "Africa" },
                    { 163, "NU", "NIU", "Niue", "Oceania" },
                    { 164, "NF", "NFK", "Norfolk Island", "Oceania" },
                    { 165, "MK", "MKD", "North Macedonia", "Europe" },
                    { 166, "MP", "MNP", "Northern Mariana Islands", "Oceania" },
                    { 167, "NO", "NOR", "Norway", "Europe" },
                    { 168, "OM", "OMN", "Oman", "Asia" },
                    { 169, "PK", "PAK", "Pakistan", "Asia" },
                    { 170, "PW", "PLW", "Palau", "Oceania" },
                    { 171, "PS", "PSE", "Palestine, State of", "Asia" },
                    { 172, "PA", "PAN", "Panama", "Americas" },
                    { 173, "PG", "PNG", "Papua New Guinea", "Oceania" },
                    { 174, "PY", "PRY", "Paraguay", "Americas" },
                    { 175, "PE", "PER", "Peru", "Americas" },
                    { 176, "PH", "PHL", "Philippines", "Asia" },
                    { 177, "PN", "PCN", "Pitcairn", "Oceania" },
                    { 178, "PL", "POL", "Poland", "Europe" },
                    { 179, "PT", "PRT", "Portugal", "Europe" },
                    { 180, "PR", "PRI", "Puerto Rico", "Americas" },
                    { 181, "QA", "QAT", "Qatar", "Asia" },
                    { 182, "RE", "REU", "Réunion", "Africa" },
                    { 183, "RO", "ROU", "Romania", "Europe" },
                    { 184, "RU", "RUS", "Russian Federation", "Europe" },
                    { 185, "RW", "RWA", "Rwanda", "Africa" },
                    { 186, "BL", "BLM", "Saint Barthélemy", "Americas" },
                    { 187, "SH", "SHN", "Saint Helena, Ascension and Tristan da Cunha", "Africa" },
                    { 188, "KN", "KNA", "Saint Kitts and Nevis", "Americas" },
                    { 189, "LC", "LCA", "Saint Lucia", "Americas" },
                    { 190, "MF", "MAF", "Saint Martin (French part)", "Americas" },
                    { 191, "PM", "SPM", "Saint Pierre and Miquelon", "Americas" },
                    { 192, "VC", "VCT", "Saint Vincent and the Grenadines", "Americas" },
                    { 193, "WS", "WSM", "Samoa", "Oceania" },
                    { 194, "SM", "SMR", "San Marino", "Europe" },
                    { 195, "ST", "STP", "Sao Tome and Principe", "Africa" },
                    { 196, "SA", "SAU", "Saudi Arabia", "Asia" },
                    { 197, "SN", "SEN", "Senegal", "Africa" },
                    { 198, "RS", "SRB", "Serbia", "Europe" },
                    { 199, "SC", "SYC", "Seychelles", "Africa" },
                    { 200, "SL", "SLE", "Sierra Leone", "Africa" },
                    { 201, "SG", "SGP", "Singapore", "Asia" },
                    { 202, "SX", "SXM", "Sint Maarten (Dutch part)", "Americas" },
                    { 203, "SK", "SVK", "Slovakia", "Europe" },
                    { 204, "SI", "SVN", "Slovenia", "Europe" },
                    { 205, "SB", "SLB", "Solomon Islands", "Oceania" },
                    { 206, "SO", "SOM", "Somalia", "Africa" },
                    { 207, "ZA", "ZAF", "South Africa", "Africa" },
                    { 208, "GS", "SGS", "South Georgia and the South Sandwich Islands", "Americas" },
                    { 209, "SS", "SSD", "South Sudan", "Africa" },
                    { 210, "ES", "ESP", "Spain", "Europe" },
                    { 211, "LK", "LKA", "Sri Lanka", "Asia" },
                    { 212, "SD", "SDN", "Sudan", "Africa" },
                    { 213, "SR", "SUR", "Suriname", "Americas" },
                    { 214, "SJ", "SJM", "Svalbard and Jan Mayen", "Europe" },
                    { 215, "SE", "SWE", "Sweden", "Europe" },
                    { 216, "CH", "CHE", "Switzerland", "Europe" },
                    { 217, "SY", "SYR", "Syrian Arab Republic", "Asia" },
                    { 218, "TW", "TWN", "Taiwan, Province of China", "Asia" },
                    { 219, "TJ", "TJK", "Tajikistan", "Asia" },
                    { 220, "TZ", "TZA", "Tanzania, United Republic of", "Africa" },
                    { 221, "TH", "THA", "Thailand", "Asia" },
                    { 222, "TL", "TLS", "Timor-Leste", "Asia" },
                    { 223, "TG", "TGO", "Togo", "Africa" },
                    { 224, "TK", "TKL", "Tokelau", "Oceania" },
                    { 225, "TO", "TON", "Tonga", "Oceania" },
                    { 226, "TT", "TTO", "Trinidad and Tobago", "Americas" },
                    { 227, "TN", "TUN", "Tunisia", "Africa" },
                    { 228, "TR", "TUR", "Turkey", "Asia" },
                    { 229, "TM", "TKM", "Turkmenistan", "Asia" },
                    { 230, "TC", "TCA", "Turks and Caicos Islands", "Americas" },
                    { 231, "TV", "TUV", "Tuvalu", "Oceania" },
                    { 232, "UG", "UGA", "Uganda", "Africa" },
                    { 233, "UA", "UKR", "Ukraine", "Europe" },
                    { 234, "AE", "ARE", "United Arab Emirates", "Asia" },
                    { 235, "GB", "GBR", "United Kingdom of Great Britain and Northern Ireland", "Europe" },
                    { 236, "US", "USA", "United States of America", "Americas" },
                    { 237, "UM", "UMI", "United States Minor Outlying Islands", "Oceania" },
                    { 238, "UY", "URY", "Uruguay", "Americas" },
                    { 239, "UZ", "UZB", "Uzbekistan", "Asia" },
                    { 240, "VU", "VUT", "Vanuatu", "Oceania" },
                    { 241, "VE", "VEN", "Venezuela (Bolivarian Republic of)", "Americas" },
                    { 242, "VN", "VNM", "Viet Nam", "Asia" },
                    { 243, "VG", "VGB", "Virgin Islands (British)", "Americas" },
                    { 244, "VI", "VIR", "Virgin Islands (U.S.)", "Americas" },
                    { 245, "WF", "WLF", "Wallis and Futuna", "Oceania" },
                    { 246, "EH", "ESH", "Western Sahara", "Africa" },
                    { 247, "YE", "YEM", "Yemen", "Asia" },
                    { 248, "ZM", "ZMB", "Zambia", "Africa" },
                    { 249, "ZW", "ZWE", "Zimbabwe", "Africa" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Countries");
        }
    }
}
